/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tum_in_far_threedui_elsim_Simulation */

#ifndef _Included_de_tum_in_far_threedui_elsim_Simulation
#define _Included_de_tum_in_far_threedui_elsim_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    getNodes
 * Signature: ()[Lde/tum/in/far/threedui/elsim/NodeInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_getNodes
  (JNIEnv *, jobject);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    addAtom
 * Signature: (Ljava/lang/String;FFF)I
 */
JNIEXPORT jint JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_addAtom
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    removeAtom
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_removeAtom
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    CanConnect
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_CanConnect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    Connect
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_Connect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    Disconnect
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_Disconnect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    removeMolecule
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_removeMolecule
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    setAtomPosition
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_setAtomPosition
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    freeAtomPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_freeAtomPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_init
  (JNIEnv *, jobject);

/*
 * Class:     de_tum_in_far_threedui_elsim_Simulation
 * Method:    getRotationToTarget
 * Signature: (Ljavax/vecmath/Vector3d;Ljavax/vecmath/Vector3d;)Ljavax/vecmath/Vector3d;
 */
JNIEXPORT jobject JNICALL Java_de_tum_in_far_threedui_elsim_Simulation_getRotationToTarget
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
